version: "3"

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENABLE_FLAC=${ENABLE_FLAC:-0}
    volumes:
      - type: volume
        source: ./cookies.txt
        target: /tmp/cookies.txt
        read_only: true
    restart: always
    env_file:
      - token.env
